on:
  poll:
    url:
      # haneame
      - "https://my-api.redpeacock78.com/v1/kemono/posts/patreon/4626321"
      # Ceo_neet
      - "https://my-api.redpeacock78.com/v1/kemono/posts/patreon/13200612"
      # Punpunn
      - "https://my-api.redpeacock78.com/v1/kemono/posts/patreon/4113620"
      # 牛と鶏MMD
      - "https://my-api.redpeacock78.com/v1/kemono/posts/patreon/87993999"
      # easonx
      - "https://my-api.redpeacock78.com/v1/kemono/posts/patreon/9961216"
      # Oniilus
      - "https://my-api.redpeacock78.com/v1/kemono/posts/patreon/4890821"
      # Sakimichan
      - "https://my-api.redpeacock78.com/v1/kemono/posts/patreon/371321"
      # Kuuko_w
      - "https://my-api.redpeacock78.com/v1/kemono/posts/patreon/6889522"
      # LK00
      - "https://my-api.redpeacock78.com/v1/kemono/posts/patreon/14671789"
      # TRYLSC
      - "https://my-api.redpeacock78.com/v1/kemono/posts/patreon/641867"
      # nlch
      - "https://my-api.redpeacock78.com/v1/kemono/posts/patreon/8762407"
      # JygreAnimation
      - "https://my-api.redpeacock78.com/v1/kemono/posts/patreon/68124575"
      # shiroganesama
      - "https://my-api.redpeacock78.com/v1/kemono/posts/patreon/6456308"
      # アヘ丸
      - "https://my-api.redpeacock78.com/v1/kemono/posts/patreon/7842696"
      # k8on
      - "https://my-api.redpeacock78.com/v1/kemono/posts/patreon/59916205"
      # OSNET
      - "https://my-api.redpeacock78.com/v1/kemono/posts/patreon/16538141"
      # PanPiano
      - "https://my-api.redpeacock78.com/v1/kemono/posts/patreon/14045281"
      # PoPer
      - "https://my-api.redpeacock78.com/v1/kemono/posts/patreon/57431512"
    itemsPath: items
    deduplicationKey: id
    buildOutputsOnError: true
    config:
      skipOnError: true
      format: |
        item.title = item.title.replace(/'/g, "'\\''");
        return item;
jobs:
  post:
    name: Post kemono-api updates to the discord
    runs-on: ubuntu-latest
    steps:
      - name: Fix
        id: fix
        run: |
          fix_title=$(echo '${{ on.poll.outputs.title }}' | sed "s/'/'\\\''/g" | sed 's/!/\\!/g;s/"/\\"/g;s/*/\\\\*/g;s/_/\\\\_/g;s/~~/\\\\~~/g')
          sourseName=$(awk -F "/" '{print $4}' <<<"${{ on.poll.outputs.contentUrl }}")
          userId=$(awk -F "/" '{print $6}' <<<"${{ on.poll.outputs.contentUrl }}")
          contentId=$(awk -F "/" '{print $8}' <<<"${{ on.poll.outputs.contentUrl }}")
          fix_url="https://${{ secrets.API_DOMAIN }}/v1/kemono/posts/${sourseName}/${userId}/${contentId}"
          echo "::set-output name=title::${fix_title}"
          echo "::set-output name=link::${fix_url}"
      - name: Post
        run: |
          {
            imageUrl=$(curl -s --retry 10 --retry-all-errors -H 'User-Agent: Discordbot' ${{ steps.fix.outputs.link }}|grep 'property="og:image"'|sed 's/^ *<meta property="og:image" content="//g;s/" \/>$//g')
            curl -s \
                 --retry 10 \
                 --retry-all-errors \
                 "${imageUrl}" > /dev/null 2>&1 || :
            curl -s \
                 -X POST \
                 --retry 10 \
                 --retry-all-errors \
                 -H "Content-Type: application/json" \
                 ${{ secrets.DISCORD_KEMONO_PATREON }} \
                 -d '{"content": "**${{ steps.fix.outputs.title }}** ${{ steps.fix.outputs.link }}"}' || :
          }
          sleep 1
