on:
  poll:
    url:
      # 日南(Canan)
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fantia/83679"
      # Lenfried
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fantia/17213"
      # アヘ丸
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fantia/5679"
      # 月乃ウサギ
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fantia/28905"
      # Nagisa魔物喵
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fantia/17148"
      # ベルゼ
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fantia/146867"
      # 夏目つなり(@Tsunapoe)
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fantia/20001"
      # ピンキーWeb/Pinkyweb
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fantia/1445"
      # せっくすふれんど
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fantia/1470"
      # 同人アキバ出版
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fantia/4483"
      # くろこげママ🍼
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fantia/29318"
      # すごい火
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fantia/145129"
      # 長そで
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fantia/17096"
      # 岡田ゆい
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fantia/16490"
      # いわお
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fantia/478099"
      # ふらう
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fantia/2156"
      # 八木戸マト
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fantia/105571"
      # デコ助
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fantia/14553"
      # ヘルシーマン
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fantia/26643"
      # あのん２億年
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fantia/6345"
      # りお❤️❤️❤️
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fantia/158016"
      # りお❤️❤️❤️
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fantia/33044"
      # １億年惑星
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fantia/214727"
      # 左門しう
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fantia/61137"
      # ニート社長
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fantia/750"
      # horosuke
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fantia/7439"
      # とこまやけいた
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fantia/173796"
      # ぱすた
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fantia/292282"
      # おとぎてつろう
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fantia/52698"
      # 調四季
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fantia/17006"
      # コントレンジ
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fantia/40576"
      # カオム
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fantia/2065"
      # なすな
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fantia/14079"
      # akaomi
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fantia/2820"
      # LK
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fantia/32450"
      # かなみルボン
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fantia/191567"
      # ゼツレッド
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fantia/16749"
      # Rindou
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fantia/29013"
      # かすみ＠ハイパーアクティブオナニスト
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fantia/16365"
      # vanadium
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fantia/206952"
      # 焼肉大好きあきち
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fantia/376503"
      # モグダン
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fantia/6099"
      # 嫉妬マスク
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fantia/82773"
      # 隣人ちゃん@透明バニー🐰❤
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fantia/17185"
      # かりん👻
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fantia/420714"
      # バーバリアン高本
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fantia/112298"
      # ゆゆこ
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fantia/56489"
      # 山田太郎
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fantia/56142"
      # なわけな
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fantia/10720"
      # ろっぴー
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fantia/25268"
      # ky.
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fantia/12172"
      # 林檎蜜紀
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fantia/13265"
      # 白虎ルナ🐯えもえちプロダクション🐯🌙
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fantia/473831"
      # 高遠くろ助
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fantia/5306"
      # C-Low
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fantia/1736"
      # 牛虎たつみ
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fantia/76218"
      # 伊島ユウ
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fantia/100663"
      # 2=8
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fantia/2102"
      # あちゃ
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fantia/119451"
      # にぎりうさぎ
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fantia/25798"
      # ただたか
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fantia/26757"
      # にゃん子
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fantia/224711"
      # にゃん子
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fantia/415331"
      # しゃな&弥生
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fantia/102140"
      # フリム
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fantia/5644"
      # らむだ
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fantia/101032"
      # 青ばなな
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fantia/6173"
      # OSNET
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fantia/39741"
      # 蛇腹トルネード
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fantia/16538"
    itemsPath: items
    deduplicationKey: id
    buildOutputsOnError: true
    config:
      skipOnError: true
      format: |
        item.title = item.title.replace(/'/g, "'\\''");
        return item;
jobs:
  post:
    name: Post kemono-api updates to the discord
    runs-on: ubuntu-latest
    steps:
      - name: Fix
        id: fix
        run: |
          fix_title=$(echo '${{ on.poll.outputs.title }}' | sed "s/'/'\\\''/g" | sed 's/!/\\!/g;s/"/\\"/g;s/*/\\\\*/g;s/_/\\\\_/g;s/~~/\\\\~~/g')
          sourseName=$(awk -F "/" '{print $4}' <<<"${{ on.poll.outputs.contentUrl }}")
          userId=$(awk -F "/" '{print $6}' <<<"${{ on.poll.outputs.contentUrl }}")
          contentId=$(awk -F "/" '{print $8}' <<<"${{ on.poll.outputs.contentUrl }}")
          fix_url="https://${{ secrets.API_DOMAIN }}/v1/kemono/posts/${sourseName}/${userId}/${contentId}"
          echo "::set-output name=title::${fix_title}"
          echo "::set-output name=link::${fix_url}"
      - name: Post
        run: |
          {
            imageUrl=$(curl -s -H 'User-Agent: Discordbot' ${{ steps.fix.outputs.link }}|grep 'property="og:image"'|sed 's/^ *<meta property="og:image" content="//g;s/" \/>$//g')
            curl -s \
                 --retry 10 \
                 --retry-all-errors \
                 "${imageUrl}" > /dev/null 2>&1 || :
            curl -s \
                 -X POST \
                 --retry 10 \
                 --retry-all-errors \
                 -H "Content-Type: application/json" \
                 ${{ secrets.DISCORD_KEMONO_FANTIA }} \
                 -d '{"content": "**${{ steps.fix.outputs.title }}** ${{ steps.fix.outputs.link }}"}' || :
          } || exit 0
          sleep 1
