on:
  poll:
    url:
      # しょんなア
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fanbox/68051251"
      # べよん
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fanbox/1090288"
      # 消すぐあ
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fanbox/72050055"
      # Bow
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fanbox/50452"
      # えっちなサナダくん
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fanbox/35062437"
      # トリヤロウ
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fanbox/50731293"
      # 譲葉
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fanbox/9407"
      # ぷ玉
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fanbox/57068482"
      # chickeiii
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fanbox/9752301"
      # 猫作
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fanbox/14878102"
      # ちーちち
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fanbox/60960573"
      # カケタイナー　
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fanbox/30435589"
      # じんタロウ
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fanbox/78013438"
      # 朧月
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fanbox/6713"
      # DaRoon5
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fanbox/52640474"
      # しろのぶらうす
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fanbox/72966337"
      # ぱすた
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fanbox/62211057"
      # 貝
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fanbox/15076523"
      # ピリオドÖ
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fanbox/27865046"
      # 信じろ
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fanbox/1305253"
      # cancer
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fanbox/681032"
      # かぜなみ
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fanbox/91993794"
      # なわけな
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fanbox/32254275"
      # 篠崎 うい
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fanbox/16890775"
      # musouduki
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fanbox/163246"
      # ふらう
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fanbox/18340266"
      # もみさん
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fanbox/8980751"
      # 白土
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fanbox/30563163"
      # さ抜き
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fanbox/9888246"
      # 中瀬古
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fanbox/886486"
      # YoRoZ
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fanbox/16871271"
      # セナ
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fanbox/62022223"
    itemsPath: items
    deduplicationKey: id
    buildOutputsOnError: true
    config:
      skipOnError: true
      format: |
        item.title = item.title.replace(/'/g, "'\\''");
        return item;
jobs:
  post:
    name: Post kemono-api updates to the discord
    runs-on: ubuntu-latest
    steps:
      - name: Fix
        id: fix
        run: |
          fix_title=$(echo '${{ on.poll.outputs.title }}' | sed "s/'/'\\\''/g" | sed 's/!/\\!/g;s/"/\\"/g;s/*/\\\\*/g;s/_/\\\\_/g;s/~~/\\\\~~/g')
          sourseName=$(awk -F "/" '{print $4}' <<<"${{ on.poll.outputs.contentUrl }}")
          userId=$(awk -F "/" '{print $6}' <<<"${{ on.poll.outputs.contentUrl }}")
          contentId=$(awk -F "/" '{print $8}' <<<"${{ on.poll.outputs.contentUrl }}")
          fix_url="https://${{ secrets.API_DOMAIN }}/v1/kemono/posts/${sourseName}/${userId}/${contentId}"
          echo "::set-output name=title::${fix_title}"
          echo "::set-output name=link::${fix_url}"
      - name: Post
        run: |
          {
            imageUrl=$(curl -s -H 'User-Agent: Discordbot' ${{ steps.fix.outputs.link }}|grep 'property="og:image"'|sed 's/^ *<meta property="og:image" content="//g;s/" \/>$//g')
            curl -s \
                 --retry 10 \
                 --retry-all-errors \
                 "${imageUrl}" > /dev/null 2>&1 || :
            curl -s \
                 -X POST \
                 --retry 10 \
                 --retry-all-errors \
                 -H "Content-Type: application/json" \
                 ${{ secrets.DISCORD_KEMONO_FANBOX }} \
                 -d '{"content": "**${{ steps.fix.outputs.title }}** ${{ steps.fix.outputs.link }}"}' || :
          } || exit 0
          sleep 1
