on:
  poll:
    url:
      # Gakelzfh
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fanbox/19719823"
      # Rmxs3488
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fanbox/12501034"
      # うるりひ
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fanbox/12501034"
      # むち
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fanbox/65092407"
      # さかい
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fanbox/7140630"
      # fumihiko
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fanbox/2658856"
      # 長そで
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fanbox/14356894"
      # maru54
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fanbox/151892"
      # sou-mikagami
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fanbox/267681"
      # 猫乃またたび
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fanbox/581626"
      # 良く煮た卵
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fanbox/20098597"
      # おもだか
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fanbox/374142"
      # も
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fanbox/5835340"
      # くろたま
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fanbox/272079"
      # 雲丹ピアノ
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fanbox/65330886"
      # れもち
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fanbox/80695562"
      # あっくす
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fanbox/717665"
      # ともつか治臣
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fanbox/230418"
      # 郁(いく)
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fanbox/5476137"
      # reloco
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fanbox/70637112"
      # アメ
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fanbox/37644945"
      # サーヤ
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fanbox/39908359"
      # またんごむ
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fanbox/2316546"
      # ie
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fanbox/24164271"
      # Cosine
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fanbox/2336"
      # Karinかりん
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fanbox/18499718"
      # basuke
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fanbox/9329300"
      # 18マスター
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fanbox/39240212"
      # ミモネル
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fanbox/112519"
      # おきょう
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fanbox/18960704"
      # エビ王
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fanbox/63828616"
      # おおおおありくい
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fanbox/35801"
      # ulsyan
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fanbox/41183137"
      # 水聖のあ
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fanbox/79095966"
      # TERテア
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fanbox/206708"
      # susu
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fanbox/344729"
      # cham22
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fanbox/16456081"
      # ゼツレッド
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fanbox/2587756"
      # mamimi
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fanbox/17151277"
      # 寿司二郎 SushiJjiro
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fanbox/83835745"
    itemsPath: items
    deduplicationKey: id
    buildOutputsOnError: true
    config:
      skipOnError: true
      format: |
        item.title = item.title.replace(/'/g, "'\\''");
        return item;
jobs:
  post:
    name: Post kemono-api updates to the discord
    runs-on: ubuntu-latest
    steps:
      - name: Fix
        id: fix
        run: |
          fix_title=$(echo '${{ on.poll.outputs.title }}' | sed "s/'/'\\\''/g" | sed 's/!/\\!/g;s/"/\\"/g;s/*/\\\\*/g;s/_/\\\\_/g;s/~~/\\\\~~/g')
          sourseName=$(awk -F "/" '{print $4}' <<<"${{ on.poll.outputs.contentUrl }}")
          userId=$(awk -F "/" '{print $6}' <<<"${{ on.poll.outputs.contentUrl }}")
          contentId=$(awk -F "/" '{print $8}' <<<"${{ on.poll.outputs.contentUrl }}")
          fix_url="https://${{ secrets.API_DOMAIN }}/v1/kemono/posts/${sourseName}/${userId}/${contentId}"
          echo "::set-output name=title::${fix_title}"
          echo "::set-output name=link::${fix_url}"
      - name: Post
        run: |
          {
            imageUrl=$(curl -s --retry 10 --retry-all-errors -H 'User-Agent: Discordbot' ${{ steps.fix.outputs.link }}|grep 'property="og:image"'|sed 's/^ *<meta property="og:image" content="//g;s/" \/>$//g')
            curl -s \
                 --retry 10 \
                 --retry-all-errors \
                 "${imageUrl}" > /dev/null 2>&1 || :
            curl -s \
                 -X POST \
                 --retry 10 \
                 --retry-all-errors \
                 -H "Content-Type: application/json" \
                 ${{ secrets.DISCORD_KEMONO_FANBOX }} \
                 -d '{"content": "**${{ steps.fix.outputs.title }}** ${{ steps.fix.outputs.link }}"}' || :
          } || exit 0
          sleep 1
