on:
  poll:
    url:
      # あろおん
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fanbox/10920453"
      # SOS
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fanbox/85720459"
      # TRY
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fanbox/1340203"
      # a🔞
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fanbox/79145351"
      # tsurugi33
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fanbox/4994"
      # あまなぎ八雲
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fanbox/82437945"
      # 一本杭
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fanbox/177996"
      # AoChoku
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fanbox/15860216"
      # 平沢＠ZenHirasawa
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fanbox/884634"
      # リコシェット
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fanbox/66409778"
      # butachang
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fanbox/79105"
      # なつみん
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fanbox/733737"
      # 4UU
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fanbox/81635207"
      # 夏目ベンケイ
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fanbox/11339300"
      # 周防パトラ/Vtuber
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fanbox/92793665"
      # yapo
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fanbox/14089"
      # miga
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fanbox/896593"
      # 乃々木
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fanbox/28934049"
      # 澤田コウ🦔
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fanbox/87689886"
      # ぽるせりん
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fanbox/15209643"
      # horosuke
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fanbox/641955"
      # たぐ@Skeb募集中なぷいこね勢
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fanbox/39814580"
      # 根田啓史
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fanbox/208166"
      # 有都あらゆる
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fanbox/3733098"
      # 高遠くろ助
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fanbox/596129"
      # ジャッキー
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fanbox/826428"
      # KIYO
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fanbox/16208698"
      # giga
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fanbox/28238559"
      # みすりるリム
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fanbox/17239664"
      # mamaloni
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fanbox/36226075"
      # ほたる
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fanbox/86005408"
      # 姉川エ
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fanbox/61151588"
      # 耳かき
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fanbox/17382278"
      # なぎと
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fanbox/3008144"
      # fan
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fanbox/50993448"
      # ろーち
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fanbox/53657640"
      # ポロロッカ
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fanbox/1463539"
      # 🔞絵描き外国人
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fanbox/87004152"
      # 真園あきら
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fanbox/32254838"
      # りんご犬
      - "https://my-api.redpeacock78.com/v1/kemono/posts/fanbox/2396"
    itemsPath: items
    deduplicationKey: id
    buildOutputsOnError: true
    config:
      skipOnError: true
      format: |
        item.title = item.title.replace(/'/g, "'\\''");
        return item;
jobs:
  post:
    name: Post kemono-api updates to the discord
    runs-on: ubuntu-latest
    steps:
      - name: Fix
        id: fix
        run: |
          fix_title=$(echo '${{ on.poll.outputs.title }}' | sed "s/'/'\\\''/g" | sed 's/!/\\!/g;s/"/\\"/g;s/*/\\\\*/g;s/_/\\\\_/g;s/~~/\\\\~~/g')
          sourseName=$(awk -F "/" '{print $4}' <<<"${{ on.poll.outputs.contentUrl }}")
          userId=$(awk -F "/" '{print $6}' <<<"${{ on.poll.outputs.contentUrl }}")
          contentId=$(awk -F "/" '{print $8}' <<<"${{ on.poll.outputs.contentUrl }}")
          fix_url="https://${{ secrets.API_DOMAIN }}/v1/kemono/posts/${sourseName}/${userId}/${contentId}"
          oembed_url="https://${{ secrets.API_DOMAIN }}/v1/kemono/posts/${sourseName}/${userId}/${contentId}/oembed.json"
          echo "::set-output name=title::${fix_title}"
          echo "::set-output name=link::${fix_url}"
          echo "::set-output name=oembed::${oembed_url}"
      - name: Post
        run: |
          {
            # imageUrl=$(curl -s --retry 10 --retry-all-errors -H 'User-Agent: Discordbot' ${{ steps.fix.outputs.link }}|grep 'property="og:image"'|sed 's/^ *<meta property="og:image" content="//g;s/" \/>$//g')
            # curl -s \
            #      --retry 10 \
            #      --retry-all-errors \
            #      "${imageUrl}" > /dev/null 2>&1 || :
            for i in {1..3}; do
              curl -s \
                   --retry 10 \
                   --retry-all-errors \
                   -H 'User-Agent: Discordbot' \
                   ${{ steps.fix.outputs.link }} > /dev/null 2>&1 || :
              curl -s \
                   --retry 10 \
                   --retry-all-errors \
                   ${{ steps.fix.outputs.oembed }} > /dev/null 2>&1 || :
            done
            curl -s \
                 -X POST \
                 --retry 10 \
                 --retry-all-errors \
                 -H "Content-Type: application/json" \
                 ${{ secrets.DISCORD_KEMONO_FANBOX }} \
                 -d '{"content": "**${{ steps.fix.outputs.title }}** ${{ steps.fix.outputs.link }}"}' || :
          } || exit 0
          sleep 1
