on:
  poll:
    url:
      - "https://api.tamakasu.ga/v1/twiflix/popular"
      - "https://api.tamakasu.ga/v1/twiflix/recent"
    itemsPath: items
    deduplicationKey: id
    buildOutputsOnError: true
    config:
      skipOnError: true

jobs:
  post:
    name: Post twiflix-api updates to the discord
    runs-on: ubuntu-latest
    steps:
      - name: Post
        run: |
          name=$(awk -F '/' '{print $NF}' <<<${{ on.poll.outputs.videoUrl }})
          link="${{ on.poll.outputs.tweetUrl }}"
          { 
            aria2c -q -x5 ${{ on.poll.outputs.videoUrl }} -o ${name}
            type=$(awk -F ',' '{print $1}' <<<$(file -b "./${name}"))
            if [[ "${{ on.poll.outputs.category }}" == "popular" ]]; then
              webhook=${{ secrets.DISCORD_TWIFLIX_POPULAR }}
            elif [[ "${{ on.poll.outputs.category }}" == "recent" ]]; then
              webhook=${{ secrets.DISCORD_TWIFLIX_RECENT }}
            fi
            if [[ "${type}" =~ "ISO Media" ]]; then
              curl -s \
                -F "file1=@${name}" \
                -F "payload_json={\"content\": \"${link}\"}" \
                ${webhook}
            fi
            rm -rf "./${name}"
          } || exit 0
