on:
  poll:
    url:
      - "https://api.redpeacock78.ml/v1/twihub/24hour"
      - "https://api.redpeacock78.ml/v1/twihub/3days"
      - "https://api.redpeacock78.ml/v1/twihub/1week"
      - "https://api.redpeacock78.ml/v1/twihub/dendou"
      - "https://api.redpeacock78.ml/v1/twihub/history"
    itemsPath: items
    deduplicationKey: id
    buildOutputsOnError: true
    config:
      skipOnError: true

jobs:
  post:
    name: Post twihub-api updates to the discord
    runs-on: ubuntu-latest
    steps:
      - name: Post
        run: |
          name=$(awk -F '/' '{print $NF}' <<<${{ on.poll.outputs.videoUrl }})
          link="${{ on.poll.outputs.tweetUrl }}"
          { 
            aria2c -q -x5 ${{ on.poll.outputs.videoUrl }} -o ${name}
            type=$(awk -F ',' '{print $1}' <<<$(file -b "./${name}"))
            if [[ "${{ on.poll.outputs.category }}" == "24hours" ]]; then
              webhook=${{ secrets.DISCORD_TWIHUB_24HOURS }}
            elif [[ "${{ on.poll.outputs.category }}" == "3days" ]]; then
              webhook=${{ secrets.DISCORD_TWIHUB_3DAYS }}
            elif [[ "${{ on.poll.outputs.category }}" == "1week" ]]; then
              webhook=${{ secrets.DISCORD_TWIHUB_1WEEK }}
            elif [[ "${{ on.poll.outputs.category }}" == "dendou" ]]; then
              webhook=${{ secrets.DISCORD_TWIHUB_DENDOU }}
            elif [[ "${{ on.poll.outputs.category }}" == "history" ]]; then
              webhook=${{ secrets.DISCORD_TWIHUB_HISTORY }}
            fi
            if [[ "${type}" =~ "ISO Media" ]]; then
              curl -s \
                -F "file1=@${name}" \
                -F "payload_json={\"content\": \"${link}\"}" \
                ${webhook}
            fi
            rm -rf "./${name}"
          } || exit 0
