name: Reset Actionsflow Cache
on:
  workflow_dispatch:
jobs:
  reset:
    runs-on: ubuntu-latest
    name: Reset Actionsflow Cache
    steps:
      - uses: actions/checkout@v6
      - name: Run Actionsflow Clean
        uses: redpeacock78/actionsflow-action@v3.1.4
        with:
          args: clean
          json-secrets: ${{ toJSON(secrets) }}
